ZealandZooEksamen/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ZealandZooEksamen.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ZealandZooEksamen/Pages/EventCRUD/CreateEvent.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ZealandZooEksamen.Model;
using ZealandZooEksamen.Services;

//User story 1 Kader

namespace ZealandZooEksamen.Pages.EventCRUD
{
    public class CreateEventModel : PageModel
    {
        private IEventService _eventService;

        [BindProperty]
        public Event OpretEvent { get; set; }

        public CreateEventModel(IEventService eventService)
        {
            _eventService = eventService;
        }
        
        public IActionResult OnPostOpret()
        {
            _eventService.CreateEvent(OpretEvent);

            return RedirectToPage("/Admin");
        }
    }
}

ZealandZooEksamen/Pages/Homepage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ZealandZooEksamen.Pages
{
    public class HomepageModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ZealandZooEksamen/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using ZealandZooEksamen.Services;
using ZealandZooEksamen.Model;
using ZealandZooEksamen.Services;
using ZealandZooEksamen.Userstory_12;
using ZealandZooEksamen.UserStory_12;
using Microsoft.AspNetCore.Mvc;

namespace ZealandZooEksamen.Pages
{
    public class IndexModel : PageModel
    {
        private IEventService _service;
        private IPersonService _personService;
        private IUserService _userservice;



        public IndexModel(IEventService service, IPersonService personService)
        {
            _service = service;

            _personService = personService;


           

        }
        public List<Event> Events { get; set; }
        public List<Person> Personer { get; set; }


        public IActionResult OnGet()
        {
            Events = _service.GetAllEvents();
            Personer = _personService.GetAllPerson();

            _userservice = SessionHelper.GetUser(HttpContext);
            if (!_userservice.IsLoggedIn)
            {
                return RedirectToPage("Login");
            }

            return Page();
        }

      
        //login
        

        public bool IsAdmin
        {
            get
            {
                return _userservice.IsUserAdmin;
            }
        }

        public String Name => _userservice.UserName;
    }
}

ZealandZooEksamen/Pages/Kalender/Kalender.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ZealandZooEksamen.Model;
using ZealandZooEksamen.Services;

namespace ZealandZooEksamen.Pages
{
    public class KalenderModel : PageModel
    {
        private IEventService _kalenderService;
        public KalenderModel(IEventService kalenderService)
        {
            _kalenderService = kalenderService;
        }
        public List<Event> Events { get; set; }
        public void OnGet()
        {
            Events = _kalenderService.GetAllEvents();
        }
        public IActionResult OnPost(int dag)
        {
            string kalenderDag = HentDag(dag);
            Events = _kalenderService.GetAllEvents();
            Event? ev = Events.Find(e => e.Dato == kalenderDag);

            if (ev is null)
            {
                return Page();
            }

            return RedirectToPage("KalenderEvent", new { eventId = ev.EventId });
        }
        public bool HasEvent(int dag)
        {
            string kalenderDag = HentDag(dag);

            return Events.Any(e => e.Dato == kalenderDag);
        }

        private static string HentDag(int dag)
        {
            string kalenderDag = "";
            if (dag < 10)
            {
                kalenderDag = "2023-06-0" + dag;
            }
            else
            {
                kalenderDag = "2023-06-" + dag;
            }

            return kalenderDag;
        }
    }
}

ZealandZooEksamen/Pages/KalenderEvent.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ZealandZooEksamen.Model;
using ZealandZooEksamen.Services;

namespace ZealandZooEksamen.Pages
{
    public class KalenderEventModel : PageModel
    {
        private IEventService _service;

        [BindProperty]
        public Event SeEvent { get; set; }

        public KalenderEventModel(IEventService service)
        {
            _service = service;
        }
        public void OnGet(int eventId)
        {
            SeEvent = _service.FindEvent(eventId);
        }
        public IActionResult OnPostTilbage()
        {
            return RedirectToPage("Index");
        }
    }
}

ZealandZooEksamen/Pages/KalenderNoEvent.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ZealandZooEksamen.Pages
{
    public class KalenderNoEventModel : PageModel
    {
        public void OnGet()
        {
        }
        public IActionResult OnPostTilbage()
        {
            return RedirectToPage("Index");
        }
    }
}

ZealandZooEksamen/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ZealandZooEksamen.Services;

namespace ZealandZooEksamen.Pages
{
    //Kader
    public class LogoutModel : PageModel
    {
        private IUserService _userservice;

        public LogoutModel()
        {

        }

        public IActionResult OnGet()
        {
            _userservice = SessionHelper.GetUser(HttpContext);
            _userservice.UserLoggedOut();
            SessionHelper.SetUser(_userservice, HttpContext);

            return RedirectToPage("Index");
        }
    }
}

ZealandZooEksamen/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ZealandZooEksamen.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ZealandZooEksamen/Pages/TilmeldteCR/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ZealandZooEksamen.Pages.TilmeldteCR
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ZealandZooEksamen/Pages/EventCRUD/CreateEvent.cshtml
@page
@model ZealandZooEksamen.Pages.EventCRUD.CreateEventModel
@{
}
@*Kader*@
@if (ZealandZooEksamen.Services.UserService.iAmAdmin)
{
<body class="bg-light">
    <div class="row">
        <div class="col-md-6 text-black bg-yellow rounded-2">
            <form method="post" onsubmit="return validateTimes()">

                @*<div class="form-group">
                    <label asp-for="@Model.OpretEvent.EventId" class="control-label">Event Id</label><br>
                    <input asp-for="@Model.OpretEvent.EventId" class="form-control-sm" /><br>
                </div>*@


                <div class="form-group">
                    <label asp-for="@Model.OpretEvent.Navn" class="control-label">Event Navn</label><br>
                    <input asp-for="@Model.OpretEvent.Navn" class="form-control-sm" required /><br>
                </div>

                <div class="form-group">
                    <label asp-for="@Model.OpretEvent.EventInfo" class="control-label">Event Info</label><br>
                    <input asp-for="@Model.OpretEvent.EventInfo" class="form-control-sm" required /><br>
                </div>

            <div class="form-group">
                <label for="dato">Dato:</label>
                <input type="date" asp-for="@Model.OpretEvent.Dato" class="form-control" required /><br />
            </div>
     
            <div class="form-group">
                <label>Start tid</label><br>
                <input type="time" asp-for="@Model.OpretEvent.TimeStart" id="startTime" class="form-control" required /><br />
            </div>

            <div class="form-group">
                <label>Slut tid</label><br>
                <input type="time" asp-for="@Model.OpretEvent.TimeEnd" id="endTime" class="form-control" required /><br />
                <span asp-validation-for="@Model.OpretEvent.TimeEnd" class="text-danger"></span>
  
                <script>
                    function validateTimes() 
                    {
                        var startTime = document.getElementById('startTime').value;
                        var endTime = document.getElementById('endTime').value;

                        if (endTime < startTime) 
                        {
                            alert('Slut tid kan ikke være før Start tid.');
                            return false;
                        }

                        return true; 
                    }
                </script>
            </div>

                <div class="form-group">
                    <label>Maks antal deltagere</label><br>
                    <input asp-for="@Model.OpretEvent.MaksDeltagere" class="form-control-sm" required /><br />
                </div>

                @*<div class="form-group">
                    <input type="hidden" asp-for="@Model.OpretEvent.AntalDeltagere"/>
                    <label>Antal deltagere</label><br>
                    <input asp-for="@Model.OpretEvent.AntalDeltagere" class="form-control-sm" /><br />
                </div>*@
            
                <br />
                <div class="form-group">
                    <input type="submit" class="btn btn-success form-col" value="Opret Event" asp-page-handler="Opret" />
                </div>
                <br />
                <div class="form-group">
                    <a class="btn btn-danger form-col" asp-page="/Admin">Fortryd</a>
                </div>
                <br />
            </form>
        </div>
    </div>
</body>
}

ZealandZooEksamen/Pages/EventCRUD/DeleteEvent.cshtml
@page
@model ZealandZooEksamen.Pages.EventCRUD.DeleteEventModel
@{
    ViewData["Title"] = "Slet Event " + @Model.SletEvent.EventId;
    //ViewData["Title"] = "Slet Mock Event " + Model.SletMockEvent.EventId;
}

@*User story 14 - Magnus*@
@if (ZealandZooEksamen.Services.UserService.iAmAdmin)
{
<body class="bg-light">
<div class="row">
    <div class="col-sm-3 text-black bg-yellow rounded-2">
        @*<p>Event Id: @Model.SletMockEvent.EventId</p>
        <p>Event Navn: @Model.SletMockEvent.Navn</p>
        <p>Event Dato: @Model.SletMockEvent.Dato</p>
        <p>Event Info: @Model.SletMockEvent.EventInfo</p>
        <p>Event Antal Deltagere: @Model.SletMockEvent.AntalDeltagere</p>
        <p>Event Maksimum Deltagere: @Model.SletMockEvent.MaksDeltagere</p>
        <p>Event Start Tid: @Model.SletMockEvent.TimeStart</p>
        <p>Event Slut Tid: @Model.SletMockEvent.TimeEnd</p>*@
        
            <p>Id: @Model.SletEvent.EventId</p>
            <p>Navn: @Model.SletEvent.Navn</p>
            <p>Dato: @Model.SletEvent.Dato</p>
            <p>Info: @Model.SletEvent.EventInfo</p>
            <p>Antal Deltagere: @Model.Tæler(Model.SletEvent.EventId)</p>
            <p>Maksimum Deltagere: @Model.SletEvent.MaksDeltagere</p>
            <p>Start Tid: @Model.SletEvent.TimeStart</p>
            <p>Slut Tid: @Model.SletEvent.TimeEnd</p>
        
            <p></p>
            <form method="post">
                <div class="form-group">
                    @*<input type="submit" value="Slet Event" asp-page-handler="Slet" asp-route-eventId="@Model.SletMockEvent.EventId" />*@
                    <input type="submit" value="Slet Event" class="btn btn-danger" asp-page-handler="Slet" asp-route-eventId="@Model.SletEvent.EventId" />
                </div>
                <p></p>
                <div class="form-group">
                    <input type="submit" value="Fortryd" class="btn btn-primary" asp-page-handler="Fortryd" />
                </div>
                <br />
            </form>
        </div>
    </div>
</body>
}

ZealandZooEksamen/Pages/EventCRUD/EditEvent.cshtml
@page
@model ZealandZooEksamen.Pages.EventCRUD.EditEventModel
@{
    }
@*    // User Story 14 - Bjørn*@
    @if (ZealandZooEksamen.Services.UserService.iAmAdmin)
    {

<body class="bg-light">
    <div class="container border-2 rounded-2">
        <h1>Rediger @Model.Navn</h1>
        <div class="row">
            <div class="col-md-6 text-black bg-yellow rounded-2">
                <form method="post" onsubmit="return validateTimes()">
                    <div>
                        <input type="hidden" asp-for="@Model.EventId" />
                    </div>

                        <div class="form-group">
                            <label>Event Navn</label><br>
                            <input asp-for="@Model.Navn" class="form-control-sm" required /><br />
                        </div>

                        <div class="form-group">
                            <label>Event Info</label><br>
                            <input asp-for="@Model.EventInfo" class="form-control-sm" required /><br />
                            <span asp-validation-for="@Model.EventInfo" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label>Dato</label><br>
                            <input type="date" asp-for="@Model.Dato" class="form-control" required /><br />
                            <span asp-validation-for="@Model.Dato" class="text-danger"></span>
                        </div>

                    <div class="form-group">
                        <label>Start Tidspunkt</label><br>
                        <input type="time" asp-for="@Model.TimeStart" id="startTime" class="form-control" required /><br />
                        <span asp-validation-for="@Model.TimeStart" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label>Slut Tidspunkt</label><br>
                        <input type="time" asp-for="@Model.TimeEnd" id="endTime" class="form-control" required /><br />
                        <span asp-validation-for="@Model.TimeEnd" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                    <script>
                        function validateTimes() 
                        {
                            var startTime = document.getElementById('startTime').value;
                            var endTime = document.getElementById('endTime').value;

                            if (endTime < startTime) 
                            {
                                alert('Slut tid kan ikke være før Start tid.');
                                return false;
                            }

                            return true;
                        }
                    </script>
                    </div>

                    <div class="form-group">
                        <label>Maks Antal Deltagere</label><br>
                        <input asp-for="@Model.MaksDeltagere" class="form-control-sm" required /><br />
                        <span asp-validation-for="@Model.MaksDeltagere" class="text-danger"></span>
                    </div>

                        @*<div class="form-group">
                        <label>Antal tilmeldte Deltagere</label><br>
                        <input asp-for="@Model.AntalDeltagere" class="form-control-sm" /><br />
                        <span asp-validation-for="@Model.AntalDeltagere" class="text-danger"></span>
                    </div>*@

                    <br />
                    <form method="post">
                        <div class="form-group">
                            <input type="submit" value="Rediger" asp-page-handler="Edit" asp-route-eventId="@Model.EventId" class="btn btn-warning" />
                        </div>
                        <br />
                        <div class="form-group">
                            <a asp-page="/Admin" class="btn btn-danger">Fortryd</a>
                        </div>
                        <br />
                    </form>
                </form>
            </div>
        </div>
    </div>
</body>
}

ZealandZooEksamen/Pages/EventCRUD/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Zealand Zoo";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


@*Magnus*@
<body class="bg-light">
    <h2>Events</h2>
    <div class="row list-group-horizontal">
        @foreach (var e in Model.Events)
        {
            <div class="card column bg-yellow">
                <div class="card-body">
                    <h5 class="card-title">@e.Navn</h5>
                    <p>@e.EventInfo</p>
                    <p><strong>@e.Dato</strong></p>
                    <p>Starter <strong>@e.TimeStart</strong></p>
                    <p>Slutter <strong>@e.TimeEnd</strong></p>
                    <p>Der er <strong>@Model.LedigePladser(e.EventId)</strong> ledige pladser</p>
                </div>
                @if (ZealandZooEksamen.Services.UserService.LoggedIn)
                {
                    <div class="card-footer">
                        @if (Model.LedigePladser(e.EventId)>0)
                        {
                            <a class="btn btn-success" asp-page="/TilmeldteCR/CreateTilmelding" asp-route-eventId="@e.EventId">Tilmeld dig her</a>
                        }
                        else
                        {
                            <a class="btn btn-danger disabled">Udsolgt</a>
                        }
                        <h6></h6>
                        <a class="btn btn-primary" asp-page="/TilmeldteCR/IndexTilmelding" asp-route-eventId="@e.EventId">Tilmeldte personer</a>
                    </div>
                }
            </div>
        }
    </div>
    <br />

 
    @*
    <h2>Tilmeldte personer (Nyhedsbrev) </h2>
    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th>Navn</th>
                <th>Telefon nr</th>
                <th>Deltager</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var person in Model.Personer)
            {
                <tr>
                    <td>@person.Id</td>
                    <td>@person.Name</td>
                    <td>@person.PhoneNumber</td>
                    <td>@person.Attending</td>
                </tr>
            }
        </tbody>
    </table>*@

    <script>
        // Her finder vi elementerne med class="column"
        var elements = document.getElementsByClassName("column");

        // Her erklære vi en variabel
        var i;

        // Her bliver vores Grid lavet
        function gridView() {
            for (i = 0; i < elements.length; i++) {
            elements[i].style.width = "25%";
            }
        }
    </script>
</body>

ZealandZooEksamen/Pages/LagerCRUD/CreateLager.cshtml
@page
@model ZealandZooEksamen.Pages.LagerCRUD.CreateLagerModel
@{
}

@*User story 10 - Bjørn*@
@if (ZealandZooEksamen.Services.UserService.iAmAdmin)
{
<body class="bg-light">
    <div class="row">
        <div class="col-md-6 text-black bg-yellow rounded-2">
            <form method="post" onsubmit="return validateNumbers()">
                <br />
                <div class="form-group">
                    <input type="hidden" asp-for="@Model.OpretLager.LagerId" />
                    @*<label asp-for="@Model.OpretLager.LagerId" class="control-label">LagerId</label><br>
                    <input asp-for="@Model.OpretLager.LagerId" class="form-control" /><br>*@
                </div>

                <div class="form-group">
                    <label>Produkt Navn</label><br>
                    <input asp-for="@Model.OpretLager.LagerNavn" class="form-control" required /><br />
                </div>

            <div class="form-group">
                <label>Antal</label><br>
                        <input asp-for="@Model.OpretLager.LagerAntal" class="form-control" type="number" min="0" max="999" title="Antal skal være tal mellem 0 og 999" required /><br />
            </div>

            <div class="form-group">
                <label>Salgs Pris</label><br>
                        <input asp-for="@Model.OpretLager.LagerPris" id="number1" type="number" min="0" max="999" title="Salgs Pris skal være tal mellem 0 og 999" class="form-control" required /><br />
                <span asp-validation-for="@Model.OpretLager.LagerPris" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Indkøbs Pris</label><br>
                        <input asp-for="@Model.OpretLager.LagerIndkøbPris" id="number2" class="form-control" type="number" min="0" max="999" title="Indkøbs Pris skal være tal mellem 0 og 999" required /><br />
                <span asp-validation-for="@Model.OpretLager.LagerPris" class="text-danger"></span>
            </div>

            <script>
                function validateNumbers() {
                    var number1Value = parseFloat(document.getElementById('number1').value);
                    var number2Value = parseFloat(document.getElementById('number2').value);

                    if (number1Value <= number2Value) {
                        alert('Indkøbs pris kan ikke være højere end Salgs pris.');
                        return false;
                    }

                    return true;
                }
            </script>

            <br />
             <div class="form-group">
                <input type="submit" value="Opret Varer" class="btn btn-success" asp-page-handler="Opret" />
            </div>
            <br />
            <div class="form-group">
                <a class="btn btn-danger" asp-page="IndexLager">Fortryd</a>
            </div>

        </form>
        
        </div>
    </div>
</body>
}

ZealandZooEksamen/Pages/LagerCRUD/DeleteLager.cshtml
@page
@model ZealandZooEksamen.Pages.LagerCRUD.DeleteLagerModel
@{
}
@*User story 10 - Bjørn*@

@if (ZealandZooEksamen.Services.UserService.iAmAdmin)
{
<body class="bg-light">
    <div class="row">
        <div class="col-sm-3 text-black bg-yellow rounded-2">
            <br />
            <p>Lager Id: @Model.SletLager.LagerId</p>
            <p>Lager Navn: @Model.SletLager.LagerNavn</p>
            <p>Lager Antal: @Model.SletLager.LagerAntal</p>
            <p>Lager Pris: @Model.SletLager.LagerPris</p>
            <p>Lager Indkøbs Pris: @Model.SletLager.LagerIndkøbPris</p>
     
        
            <p></p>
            <form method="post">
                <div class="form-group">
                
                    <input type="submit" value="Slet Varer" class="btn btn-danger" asp-page-handler="Slet" asp-route-lagerId="@Model.SletLager.LagerId" />
                </div>
                <p></p>
                <div class="form-group">
                    <input type="submit" value="Fortryd" class="btn btn-primary" asp-page-handler="Fortryd" />
                </div>
                <br />
            </form>
        </div>
    </div>
</body>
}

ZealandZooEksamen/Pages/LagerCRUD/EditLager.cshtml
@page
@model ZealandZooEksamen.Pages.LagerCRUD.EditLagerModel
@{
}
@*User story 10 - Bjørn*@


@if (ZealandZooEksamen.Services.UserService.iAmAdmin)
                        {

<body class="bg-light">
    <div class="container border-2 rounded-2">
        <h1>Ændre Varer @Model.LagerId @Model.LagerNavn</h1>
        <div class="row">
            <div class="col-md-6 text-black bg-yellow rounded-2">
                <form method="post" onsubmit="return validateNumbers()">
                    <br />
                    <div >
                    <input type="hidden" asp-for="@Model.LagerId" required />

                    </div>


                    <div class="form-group">
                        <label>Lager Navn</label><br>
                        <input asp-for="@Model.LagerNavn" class="form-control" required /><br />
                    </div>

                    <div class="form-group">
                        <label>Lager Antal</label><br>
                        <input asp-for="@Model.LagerAntal" class="form-control" required /><br />
                        <span asp-validation-for="@Model.LagerAntal" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label>Salgs Pris</label><br>
                        <input asp-for="@Model.LagerPris" id="number1" class="form-control" required /><br />
                        <span asp-validation-for="@Model.LagerPris" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label>Indkøbs Pris</label><br>
                        <input asp-for="@Model.LagerIndkøbPris" id="number2" class="form-control" required /><br />
                        <span asp-validation-for="@Model.LagerIndkøbPris" class="text-danger"></span>
                    </div>

                <script>
                    function validateNumbers() {
                        var number1Value = parseFloat(document.getElementById('number1').value);
                        var number2Value = parseFloat(document.getElementById('number2').value);

                        if (number1Value <= number2Value) {
                            alert('Indkøbs pris kan ikke være højere end Salgs pris.');
                            return false;
                        }

                        return true;
                    }
                </script>

                        <div class="form-group">
                            <input type="submit" value="Ændre @Model.LagerNavn" class="btn btn-success" asp-page-handler="Edit" asp-route-lagerId="@Model.LagerId" class="btn btn-dark" />
                        </div>
                        <p></p>
                        <div class="form-group">
                            <a class="btn btn-danger" asp-page="IndexLager">Fortryd</a>
                        </div>
                        <br />
                    </form>
            </div>
        </div>
    </div>
</body>
}

ZealandZooEksamen/Pages/LagerCRUD/IndexLager.cshtml
@page
@model ZealandZooEksamen.Pages.LagerCRUD.IndexLagerModel
@{
}
@*User story 10 - Bjørn*@



<body class="bg-light">
    <h2>Vare Lager</h2>
    <a class="btn btn-success" asp-page="CreateLager">Ny Vare</a>
    
    <table class="table table-striped table-hover bg-yellow rounded-2">
        <thead>
            <tr>
                <th>Lager Id</th>
                <th>VareNavn</th>
                <th>Antal Varer</th>
                <th>Salgspris</th>
                <th>IndkøbsPris</th>
            </tr>
        </thead>
        <tbody>
       
            @foreach (var vare in Model.Lageret)
            {
                <tr>
       

                    <td>@vare.LagerId</td>
                    <td>@vare.LagerNavn</td>
                    <td>@vare.LagerAntal</td>
                    <td>@vare.LagerPris</td>
                    <td>@vare.LagerIndkøbPris</td>

                @if (ZealandZooEksamen.Services.UserService.iAmAdmin)
                {
                    <td><a class="btn btn-warning" asp-page="EditLager" asp-route-lagerId="@vare.LagerId">Rediger vare</a></td>


                    <td><a class="btn btn-danger" asp-page="DeleteLager" asp-route-lagerId="@vare.LagerId">Slet vare</a></td>
                }
            </tr>
                

            }
        </tbody>
    </table>


    <div class="container p-3 my-3 bg-dark text-white"> Der er i alt indkøbt for <strong>@Model.UdregnIndkøb()</strong> kr. </div>
</body>

ZealandZooEksamen/Pages/SalgsCRUD/CreateSalg.cshtml
@page

@*Finder controller*@
@model ZealandZooEksamen.Pages.SalgsCRUD.CreateSalgModel
@{
    //Faneblad
    ViewData["Title"] = "CreateSalg";
}

@*HTML*@
@*Bjørn*@
@if (ZealandZooEksamen.Services.UserService.iAmAdmin)
{
<body class="bg-light">
    <div class="row">
            
            <h3>Nyt Salg</h3>
        <div class="col-md-6 text-black bg-yellow rounded-2">
                
            <form method="post">
                <div class="form-group">
                    <input type="hidden" asp-for="@Model.OpretSalg.SalgsId" />
               
                </div>

                <br />
                <div class="form-group">
                        <label> <strong>Produkt Navn</strong></label><br>
                    <p>Skriv navnet som det står i lageret (Se ude til højre-->)</p>
                    <input asp-for="@Model.OpretSalg.SalgsNavn" class="form-control" required /><br />
                </div>

                <div class="form-group">
                        <label><strong>Antal</strong> </label><br>
                    <p>Kun tal mellem 0 og 999</p>
                        <input asp-for="@Model.OpretSalg.SalgsAntal" class="form-control" type="number" min="0" max="999" title="Antal skal være tal mellem 0 og 999" required /><br />
                </div>

                <div class="form-group">
                        <label><strong>Salgs Pris</strong></label><br>
                        <p>Kun tal mellem 0 og 999</p>
                        <input asp-for="@Model.OpretSalg.SalgsPris" class="form-control" type="number" min="0" max="999" title="Salgs Pris skal være tal mellem 0 og 999" required /><br />
                    <span asp-validation-for="@Model.OpretSalg.SalgsPris" class="text-danger"></span>
                </div>


                <div class="form-group">
                    <input class="btn btn-success" type="submit" value="Opret Salg" asp-page-handler="Opret" />
                </div>
                <br />
                <div class="form-group">
                    <a class="btn btn-danger" asp-page="IndexSalg">Fortryd</a>
                </div>
                <br />

            </form>

        </div>

    <div class="col-md-6">
        <h3>Vare Lageret</h3>
                <table class="table table-striped table-hover bg-yellow rounded-2">
                    
                    <thead>
                        <tr>
                            @*<th>Lager Id</th>*@
                            <th>VareNavn</th>
                            <th>Antal Varer</th>
                            <th>Salgspris</th>
                            <th>IndkøbsPris</th>
                        </tr>
                    </thead>
                    <tbody>
                        
    @*hvert element (vare) *@
                @foreach (var vare in Model.Lageret)
                {
                            <tr>

                                @*Felter i tabel*@
                                @*<td>@vare.LagerId</td>*@
                                <td>@vare.LagerNavn</td>
                                <td>@vare.LagerAntal</td>
                                <td>@vare.LagerPris</td>
                                <td>@vare.LagerIndkøbPris</td>
                            </tr>


                }
                    </tbody>
                </table>
    </div>
</body>
}